/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisitasTecnicasRouteImport } from './routes/visitas-tecnicas'
import { Route as ProgramacaoRouteImport } from './routes/programacao'
import { Route as LocaisRouteImport } from './routes/locais'
import { Route as HospedagemRouteImport } from './routes/hospedagem'
import { Route as FotosRouteImport } from './routes/fotos'
import { Route as IndexRouteImport } from './routes/index'

const VisitasTecnicasRoute = VisitasTecnicasRouteImport.update({
  id: '/visitas-tecnicas',
  path: '/visitas-tecnicas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramacaoRoute = ProgramacaoRouteImport.update({
  id: '/programacao',
  path: '/programacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisRoute = LocaisRouteImport.update({
  id: '/locais',
  path: '/locais',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemRoute = HospedagemRouteImport.update({
  id: '/hospedagem',
  path: '/hospedagem',
  getParentRoute: () => rootRouteImport,
} as any)
const FotosRoute = FotosRouteImport.update({
  id: '/fotos',
  path: '/fotos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/hospedagem': typeof HospedagemRoute
  '/locais': typeof LocaisRoute
  '/programacao': typeof ProgramacaoRoute
  '/visitas-tecnicas': typeof VisitasTecnicasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/hospedagem': typeof HospedagemRoute
  '/locais': typeof LocaisRoute
  '/programacao': typeof ProgramacaoRoute
  '/visitas-tecnicas': typeof VisitasTecnicasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/fotos': typeof FotosRoute
  '/hospedagem': typeof HospedagemRoute
  '/locais': typeof LocaisRoute
  '/programacao': typeof ProgramacaoRoute
  '/visitas-tecnicas': typeof VisitasTecnicasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/fotos'
    | '/hospedagem'
    | '/locais'
    | '/programacao'
    | '/visitas-tecnicas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/fotos'
    | '/hospedagem'
    | '/locais'
    | '/programacao'
    | '/visitas-tecnicas'
  id:
    | '__root__'
    | '/'
    | '/fotos'
    | '/hospedagem'
    | '/locais'
    | '/programacao'
    | '/visitas-tecnicas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FotosRoute: typeof FotosRoute
  HospedagemRoute: typeof HospedagemRoute
  LocaisRoute: typeof LocaisRoute
  ProgramacaoRoute: typeof ProgramacaoRoute
  VisitasTecnicasRoute: typeof VisitasTecnicasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/visitas-tecnicas': {
      id: '/visitas-tecnicas'
      path: '/visitas-tecnicas'
      fullPath: '/visitas-tecnicas'
      preLoaderRoute: typeof VisitasTecnicasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programacao': {
      id: '/programacao'
      path: '/programacao'
      fullPath: '/programacao'
      preLoaderRoute: typeof ProgramacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais': {
      id: '/locais'
      path: '/locais'
      fullPath: '/locais'
      preLoaderRoute: typeof LocaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem': {
      id: '/hospedagem'
      path: '/hospedagem'
      fullPath: '/hospedagem'
      preLoaderRoute: typeof HospedagemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fotos': {
      id: '/fotos'
      path: '/fotos'
      fullPath: '/fotos'
      preLoaderRoute: typeof FotosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FotosRoute: FotosRoute,
  HospedagemRoute: HospedagemRoute,
  LocaisRoute: LocaisRoute,
  ProgramacaoRoute: ProgramacaoRoute,
  VisitasTecnicasRoute: VisitasTecnicasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
